### ISSUE TITLE
[DEV] Version 3.2.x Planned Features

### ISSUE THREAD

**Issue by hypherionmc** [hypherionmc/sdlink#118]
**New Features**:

- [x] Paper Support
- [x] Support for switchy mod - #75 
- [x] Support for Player Revive Mod - #107 
- [x] Multiple random discord bot statuses - #44 
- [x] Override option for custom channel/webhook for messages - #116 
- [x] Ability to translate bot messages
- [x] Support for FTB Muting System
- [x] Revisit Nickname syncing with linked names
- [x] Spam detector for command spams
- [x] Add option to disable discord chat relay - #126 

**Potential new features (if possible)**

- [x] LuckPerms integration
